import assert from 'node:assert/strict';
import {validateQuestion,gradeQuestion} from './src/question-types.js';
import {textGrade,scheduled,filterQuiz,duplicateIds,analytics,validateBackup,restoreBackup} from './src/learning-core.js';
const match=validateQuestion({type:'matching',prompt:'Match',pairs:[{left:'a',right:'1'},{left:'b',right:'2'}]});assert(gradeQuestion(match,['1','2']));assert(!gradeQuestion(match,['2','1']));
const order=validateQuestion({type:'ordering',prompt:'Order',sequence:['a','b','c']});assert(gradeQuestion(order,['a','b','c']));assert(!gradeQuestion(order,['a','c','b']));
const cloze=validateQuestion({type:'cloze',prompt:'___ and ___',blanks:['Tokyo','Paris']});assert(gradeQuestion(cloze,['Tokyo','Paris']));assert(!gradeQuestion(cloze,['Tokyo','Rome']));assert.throws(()=>validateQuestion({...cloze,prompt:'___'}));assert.throws(()=>validateQuestion({...match,pairs:[{left:'a',right:'1'},{left:'a',right:'2'}]}));
assert.equal(textGrade({answer:'Jupiter',acceptedAnswers:['Jove']},'Jove'),'correct');assert.equal(textGrade({answer:'Jupiter'},'Jupitar'),'typo');assert.equal(textGrade({answer:'cat'},'bat'),'wrong');assert.equal(textGrade({answer:'12345'},'12346'),'wrong');assert.equal(textGrade({answer:'Jupiter',fuzzy:false},'Jupitar'),'wrong');assert(gradeQuestion({answer:'東京'},'東京'));assert(!gradeQuestion({answer:'東京'},'大阪'));
const now=new Date('2026-10-04T10:00:00Z');assert.equal(scheduled({interval:10},false,now).due,'2026-10-04');assert.equal(scheduled({interval:10},true,now).interval,22);
const bank=[{id:'a',prompt:'A',answer:'A',subject:'S',topic:'T',type:'short_answer',due:'2026-10-03'},{id:'b',prompt:'B',answer:'2',subject:'S',topic:'T',type:'numeric',due:'2026-10-10'}];const controls={mode:'due',types:[],focus:'all',count:10,shuffle:false};assert.deepEqual(filterQuiz(bank,[],controls,'2026-10-04').map(x=>x.id),['a']);assert.equal(filterQuiz(bank,[],{...controls,mode:'all'}).length,2);assert.equal(filterQuiz(bank,[],{...controls,mode:'all',subject:'none'}).length,0);assert.equal(filterQuiz(bank,[],{...controls,mode:'all',types:['numeric']}).length,1);assert.equal(duplicateIds([...bank,{...bank[0],id:'c'}]).size,2);
const reports=[{id:'r',accuracy:0,questions:[{knowledge_id:'a',subject:'S',topic:'T',type:'short_answer',prompt:'A',correct:false,response_time_seconds:3}]}];assert.equal(filterQuiz(bank,reports,{...controls,focus:'weak'}).length,1);assert.equal(analytics(reports).groups.subject.S.seconds,3);
const backup={app:'RecallFlow',version:1,questions:bank,reports,quizCount:1,streakDays:['2026-10-04'],preferences:{theme:'dark',voice:'af_bella',speed:1,quiz:{count:5,shuffle:true}}};assert.equal(validateBackup(backup,validateQuestion).questions.length,2);assert.throws(()=>validateBackup({...backup,questions:[bank[0],bank[0]]},validateQuestion));
const store=new Map([['recallflow_personal_lock_v1','private-lock']]);globalThis.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)};restoreBackup(backup);assert.equal(store.get('recallflow_personal_lock_v1'),'private-lock');assert.equal(JSON.parse(store.get('recallflow_quiz_preferences_v1')).count,5);
const before=new Map(store);let once=true;localStorage.setItem=(k,v)=>{if(k==='recallflow_reports'&&once){once=false;throw new Error('quota');}store.set(k,v);};assert.throws(()=>restoreBackup({...backup,quizCount:2}));assert.deepEqual(store,before);
console.log('PASS: structured grading, conservative typos, alternatives, Unicode, schedule, quiz filters, duplicates, analytics, validated restore and quota rollback.');

