from pathlib import Path
import re
root=Path(__file__).parent
old=(root/'question-controls-1.html').read_text(encoding='utf-8-sig')
css=re.search(r'<style>(.*?)</style>',old,re.S).group(1)
phones=re.findall(r'<div class="phone line">(.*?)</div></section>',old,re.S)
base=phones[1]
base=re.sub(r'<div class="scrim"></div>.*?(?=<nav>)','',base,flags=re.S)
css+='''
.popup{position:absolute;z-index:5;top:201px;right:17px;width:245px;border:1px solid #685379;border-radius:16px;background:#302737;padding:7px;box-shadow:0 16px 38px #08050e99}.menu-item{display:flex;align-items:center;gap:13px;padding:14px 12px;border-radius:10px;color:#d8c9e5;font-size:13px}.menu-item.chosen{background:#49325f;color:#f0e1ff}.menu-icon{font-size:21px;color:#c8a0ef;width:23px;text-align:center}.menu-item small{display:block;font-size:10px;margin-top:5px;color:#b6a1c4}.menu-divider{height:1px;background:#55425f;margin:5px 8px}.export-sheet{padding-bottom:25px}.export-sheet .panel-title{align-items:center;margin-bottom:8px}.export-sheet .panel-title h2{margin:0}.export-sheet>p{line-height:1.5;margin-bottom:19px}.export-choice{display:flex;align-items:flex-start;gap:12px;padding:15px;border:1px solid #504158;border-radius:12px;margin:10px 0;background:#28222f;font-size:13px}.export-choice.selected{border-color:#b285ed;background:#392b4b}.radio{width:17px;height:17px;flex-shrink:0;border:1px solid #82708f;border-radius:50%;margin-top:1px;display:grid;place-items:center}.selected .radio{border:5px solid #ad81f0;background:white}.export-choice small{font-size:11px;line-height:1.5;color:#ad9aba;display:block;margin-top:6px}.formatlabel{font-size:11px;color:#b3a0c0;margin:19px 0 9px}.format-options{display:flex;gap:9px}.format-options span{border:1px solid #55425f;border-radius:10px;padding:10px 15px;font-size:12px;color:#bfaaca}.format-options b{background:#422d58;border:1px solid #a072d6;border-radius:10px;padding:10px 15px;font-size:12px;color:#e6ceff}.export-info{margin-top:15px;padding:12px;background:#211e27;border-radius:10px;font-size:11px;line-height:1.5;color:#b3a2bf}.export-sheet .panel-actions{margin-top:18px}.export-sheet .reset{font-size:12px}.caption{font-size:12px;color:#b5a6c4;line-height:1.5;margin:10px 2px 0}
'''
menu='<div class="popup"><div class="menu-item chosen"><span class="menu-icon">⇩</span><div>Export questions<small>Download a reusable JSON file</small></div></div><div class="menu-item"><span class="menu-icon">☑</span><div>Select questions<small>Choose several for bulk actions</small></div></div><div class="menu-divider"></div><div class="menu-item"><span class="menu-icon">⧉</span><div>Find duplicates</div></div></div>'
sheet='<div class="scrim"></div><div class="sheet export-sheet"><div class="handle"></div><div class="panel-title"><h2>Export questions</h2><span>✕</span></div><p>Keep a copy or import these questions on another device.</p><div class="export-choice selected"><span class="radio"></span><div>All questions<small>17 questions from your library</small></div></div><div class="export-choice"><span class="radio"></span><div>Current results<small>Only questions matching your search and filters</small></div></div><div class="export-choice"><span class="radio"></span><div>Choose questions<small>Select exactly which questions to export</small></div></div><div class="formatlabel">FILE FORMAT</div><div class="format-options"><b>JSON · Re-importable</b></div><div class="export-info">Includes question content and attached images. For progress, reports and settings, use Full backup in Settings.</div><div class="panel-actions"><button class="reset">Cancel</button><button class="btn primary">⇩ Download JSON</button></div></div>'
cards=''.join(f'<section class="concept"><h2>{title}</h2><div class="phone line">{base}{extra}</div><p class="caption">{caption}</p></section>' for title,extra,caption in [('B · More menu',menu,'Export lives in ⋯ beside Import. Create and Import remain immediately visible.'),('B · Export options',sheet,'Choose all questions, filtered results or a selection, then download JSON.')])
(root/'question-export-b.html').write_text(f'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RecallFlow · B export preview</title><style>{css}</style></head><body><main><h1>B with Export</h1><p>Menu placement and export sheet · mobile visual previews.</p><div class="gallery">{cards}</div></main></body></html>',encoding='utf-8')
