from pathlib import Path
import re
root=Path(__file__).parent
s=(root/'question-export-b.html').read_text(encoding='utf-8-sig')
css=re.search(r'<style>(.*?)</style>',s,re.S).group(1)
base=re.search(r'<div class="phone line">(.*?)<div class="popup">',s,re.S).group(1)
base=base.replace('<button class="btn">⇧ Import</button>','')
css+='''
.transfer-menu{position:absolute;z-index:5;top:201px;right:17px;width:263px;background:#2d2535;border:1px solid #685279;border-radius:17px;padding:8px;box-shadow:0 14px 40px #08050eaa}.transfer-item{display:flex;align-items:center;gap:13px;padding:15px 12px;color:#eadff3;font-size:13px}.transfer-item .icon{color:#c5a0f1;font-size:24px;width:24px;text-align:center}.transfer-item small{display:block;color:#b09aba;font-size:10px;margin-top:6px;line-height:1.4}.transfer-item .chev{margin-left:auto;color:#9d81b5}.transfer-item:first-child{background:#423052;border-radius:11px}.transfer-heading{padding:10px 12px 5px;color:#aa91be;font-size:10px;letter-spacing:.1em}.compact-menu{width:225px;padding:7px}.compact-menu .transfer-item{padding:14px 12px;font-size:13px}.compact-menu .transfer-item:first-child{background:none}.compact-menu .icon{font-size:20px}.tile-sheet{padding:12px 20px 25px}.tile-sheet h2{font-size:21px;margin:0 0 7px}.tile-sheet>p{font-size:11px;color:#ac99b9;margin:0 0 22px}.tiles{display:grid;grid-template-columns:1fr 1fr;gap:12px}.tile{padding:22px 15px;border:1px solid #725494;border-radius:17px;background:linear-gradient(135deg,#443151,#2b2434);min-height:153px}.tile:nth-child(2){background:linear-gradient(135deg,#2c3c3c,#242c32);border-color:#4b6b68}.tile i{font-size:30px;display:block;color:#c9a1fa;font-style:normal;margin-bottom:18px}.tile:nth-child(2) i{color:#a5d1cb}.tile b{font-size:15px;display:block}.tile small{display:block;color:#bba8c5;font-size:11px;line-height:1.5;margin-top:9px}.secondary{display:flex;align-items:center;gap:12px;border-bottom:1px solid #4a3a53;padding:17px 3px;font-size:13px;color:#d5c2e0}.secondary i{font-style:normal;color:#b390d0;font-size:19px}.tile-sheet .secondary:last-child{border:0}.transfer-note{font-size:10px;color:#9d8ba9;margin-top:17px}.action-sheet{padding:12px 21px 24px}.action-sheet h2{font-size:21px;margin:0 0 8px}.action-sheet>p{color:#a993b8;font-size:11px;margin:0 0 16px}.action-box{background:#31273b;border:1px solid #5d436d;border-radius:14px;margin:10px 0;padding:19px 15px;display:flex;gap:14px;align-items:center}.action-box:nth-of-type(3){background:#263335;border-color:#466362}.action-box i{font-size:28px;font-style:normal;color:#c7a2f0}.action-box b{display:block;font-size:15px}.action-box small{display:block;color:#bca6ca;font-size:11px;line-height:1.5;margin-top:7px}.action-box .chev{margin-left:auto;color:#b595c9}.other-actions{display:flex;gap:10px;margin-top:17px}.other-actions .btn{flex:1;font-size:11px;padding:12px 6px}.close-menu{width:100%;border:1px solid #514057;border-radius:12px;background:none;padding:14px;color:#cbb5da;font-size:12px;margin-top:20px}.menu-caption{font-size:12px;color:#b39dc4;line-height:1.5;margin:12px 2px 0}
'''
def item(title,desc,icon):
    return f'<div class="transfer-item"><span class="icon">{icon}</span><div>{title}{f"<small>{desc}</small>" if desc else ""}</div><span class="chev">›</span></div>'
menu_a='<div class="transfer-menu">'+item('Import questions','Upload a file or paste JSON','⇧')+item('Export questions','All, filtered or selected questions','⇩')+'<div class="menu-divider"></div>'+item('Select questions','','☑')+item('Find duplicates','','⧉')+'</div>'
menu_b='<div class="transfer-menu compact-menu">'+item('Import','','⇧')+item('Export','','⇩')+'<div class="menu-divider"></div>'+item('Select multiple','','☑')+item('Find duplicates','','⧉')+'</div>'
menu_c='<div class="scrim"></div><div class="sheet tile-sheet"><div class="handle"></div><div class="panel-title"><h2>Question tools</h2><span>✕</span></div><p>Bring questions in or take a copy with you.</p><div class="tiles"><div class="tile"><i>⇧</i><b>Import</b><small>Upload JSON<br>or paste questions</small></div><div class="tile"><i>⇩</i><b>Export</b><small>Download all, filtered<br>or selected questions</small></div></div><div class="secondary"><i>☑</i>Select multiple questions <span style="margin-left:auto">›</span></div><div class="secondary"><i>⧉</i>Find duplicates <span style="margin-left:auto">›</span></div></div>'
menu_d='<div class="scrim"></div><div class="sheet action-sheet"><div class="handle"></div><h2>Manage questions</h2><p>Import, export and organise your question bank.</p><div class="action-box"><i>⇧</i><div><b>Import questions</b><small>Choose a JSON file or paste its content</small></div><span class="chev">›</span></div><div class="action-box"><i>⇩</i><div><b>Export questions</b><small>Download all or choose what to include</small></div><span class="chev">›</span></div><div class="other-actions"><button class="btn">☑ Select multiple</button><button class="btn">⧉ Find duplicates</button></div><button class="close-menu">Cancel</button></div>'
variants=[('A · Descriptive dropdown',menu_a,'A compact menu with a short explanation for each transfer action.'),('B · Minimal dropdown',menu_b,'A smaller menu that keeps only action names and icons.'),('C · Two-tile bottom sheet',menu_c,'Import and Export get equal space; bulk tools sit underneath.'),('D · Stacked action sheet',menu_d,'Large tap targets, helpful descriptions and a clear Cancel button.')]
for i in range(2):
    panels=''.join(f'<section class="concept"><h2>{name}</h2><div class="phone line">{base}{menu}</div><p class="menu-caption">{caption}</p></section>' for name,menu,caption in variants[i*2:i*2+2])
    (root/f'question-transfer-menu-{i+1}.html').write_text(f'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RecallFlow · Import and Export menu</title><style>{css}</style></head><body><main><h1>Import &amp; Export inside ⋯</h1><p>Four menu styles · Create stays visible · B layout with your chosen A cards.</p><div class="gallery">{panels}</div><a href="question-transfer-menu-{2 if i==0 else 1}.html" style="display:block;margin-top:18px;color:#b89af2;font-size:12px">View the other two options →</a></main></body></html>',encoding='utf-8')
