import assert from 'node:assert/strict';
import {validateQuestion,gradeQuestion,missedItems,numericValue} from './src/question-types.js';
const make=(type,extra={})=>validateQuestion({prompt:'Question?',answer:'Yes',type,...extra});
assert.equal(make('true_false',{answer:'false'}).answer,'False');
assert.equal(gradeQuestion(make('true_false',{answer:'True'}),'False'),false);
assert.throws(()=>make('true_false'),/True or False/);
const multi=make('multi_select',{options:['A','B','C'],correctAnswers:['A','C']});
assert.equal(multi.answer,'A; C');assert.equal(gradeQuestion(multi,['C','A']),true);
assert.equal(gradeQuestion(multi,['A']),false);assert.equal(gradeQuestion(multi,['A','B','C']),false);
assert.throws(()=>make('multi_select',{options:['A','B'],correctAnswers:['C']}),/match/);
assert.throws(()=>make('single_choice',{options:['A','A'],answer:'A'}),/different/);
assert.throws(()=>make('single_choice',{options:['A','B'],answer:'C'}),/match/);
const number=make('numeric',{answer:'-3.14',numericTolerance:.01});
assert.equal(gradeQuestion(number,'-3.13'),true);assert.equal(gradeQuestion(number,'3.14'),false);
assert.equal(gradeQuestion(number,'-3.12'),false);assert.equal(gradeQuestion(number,''),false);
for(const invalid of ['Infinity','NaN','0xff','3 kg',' ',true])assert.equal(numericValue(invalid),null);
assert.equal(gradeQuestion(make('numeric',{answer:'1000'}),'1e3'),true);
assert.throws(()=>make('numeric',{answer:'5',numericTolerance:-1}),/tolerance/);
assert.equal(gradeQuestion(make('short_answer',{answer:'Tokyo'}),' tokyo! '),true);
const bank=[{id:'a',prompt:'Edited prompt'},{id:'b'},{id:'c'}];
assert.deepEqual(missedItems([{knowledge_id:'a',correct:false},{knowledge_id:'a',correct:false},{knowledge_id:'b',correct:true},{knowledge_id:'deleted',correct:false}],bank),[bank[0]]);
assert.deepEqual(missedItems([{knowledge_id:'a',correct:true}],bank),[]);
console.log('PASS: exact multi-select sets, signed numeric/tolerance grading, validation, existing text grading, retry deduplication and deleted/edited questions.');
