import React,{useState,useEffect} from 'react';
import {readSetups,writeSetups} from '../quiz-setups.js';
import {Bookmark,Check,SlidersHorizontal,Shuffle,Save,Plus} from 'lucide-react';
import {MatchingAnswer} from './QuestionInteractions';
import {Button} from './components/Button';
import {questionTypes,validateQuestion,typeLabel} from '../question-types.js';
import {filterQuiz,analytics,validateBackup,restoreBackup} from '../learning-core.js';
export function QuizBuilder({items,reports,defaults,onStart,onClose}:any){
 const initial={mode:'daily',count:defaults.count||0,subject:'',topic:'',types:[] as string[],shuffle:defaults.shuffle,focus:'all'};
 const [c,set]=useState(initial),[setups,setSetups]=useState(readSetups),[active,setActive]=useState(''),[name,setName]=useState(''),[status,setStatus]=useState('');
 const saved=setups.find(p=>p.id===active),dirty=!saved||name.trim()!==saved.name||JSON.stringify(c)!==JSON.stringify(saved.controls);
 const q=filterQuiz(items,reports,c),field=(key:string,value:any)=>{set({...c,[key]:value});setStatus('');};
 const subjects=[...new Set(items.map(x=>x.subject))].sort() as string[],topics=[...new Set(items.filter(x=>!c.subject||x.subject===c.subject).map(x=>x.topic))].sort() as string[];
 function load(p:any){set({...p.controls,types:[...p.controls.types]});setActive(p.id);setName(p.name);setStatus(`Loaded ${p.name}.`);}
 function save(){try{const preset={id:active||crypto.randomUUID(),name:name.trim(),controls:c};const next=writeSetups(active?setups.map(p=>p.id===active?preset:p):[...setups,preset]);setSetups(next);setActive(preset.id);setName(preset.name);setStatus(`Saved ${preset.name}.`);}catch(e:any){setStatus(e.message||'Could not save this setup.');}}
 return <div className="quiz-builder-v2">
 <section className="quiz-config-card"><div className="quiz-config-heading"><Bookmark size={19}/><div><h2>Saved setups</h2><p>Save your choices once. Load them whenever you need.</p></div></div>
 {setups.length?<div className="quiz-preset-list">{setups.map(p=><button key={p.id} aria-label={`Load ${p.name}`} aria-pressed={active===p.id} onClick={()=>load(p)}><Bookmark size={15}/><span><strong>{p.name}</strong><small>{p.controls.count||'All'} questions · {p.controls.mode==='all'?'All questions':p.controls.mode==='due'?'Due questions':'Daily'}{p.controls.subject?` · ${p.controls.subject}`:''}</small></span>{active===p.id&&<Check size={16}/>}</button>)}</div>:<p className="quiz-preset-empty">No saved setups yet. Choose your settings below and give them a name.</p>}
 <div className="quiz-save-preset"><label>Setup name<input maxLength={50} placeholder="e.g. Biology · quick recall" value={name} onChange={e=>{setName(e.target.value);setStatus('');}}/></label><Button disabled={!name.trim()||!dirty} onClick={save}><Save size={15}/>{active?'Save changes':'Save setup'}</Button></div>
 {active&&<div className="quiz-preset-actions"><span>{dirty?'Unsaved changes':'Saved setup loaded'}</span><button onClick={()=>{setActive('');setName('');setStatus('Name this copy to save a new setup.');}}><Plus size={13}/>Save as new</button><button disabled={!dirty} onClick={()=>saved&&load(saved)}>Reset changes</button></div>}
 <p className="quiz-save-status" role="status" aria-live="polite">{status}</p></section>
 <section className="quiz-config-card"><div className="quiz-config-heading"><SlidersHorizontal size={19}/><div><h2>Questions</h2><p>Choose the size and content of this session.</p></div></div>
 <div className="quiz-config-grid"><label>Quiz length<select value={c.count?'custom':'all'} onChange={e=>field('count',e.target.value==='all'?0:Math.min(10,Math.max(1,items.length)))}><option value="all">All matching questions</option><option value="custom">Choose a number</option></select></label>{!!c.count&&<label>Question count<input type="number" min={1} max={1000} value={c.count} onChange={e=>field('count',Math.min(1000,Math.max(1,Number(e.target.value)||1)))}/></label>}
 <label>Subject<select value={c.subject} onChange={e=>{set({...c,subject:e.target.value,topic:''});setStatus('');}}><option value="">All subjects</option>{c.subject&&!subjects.includes(c.subject)&&<option>{c.subject}</option>}{subjects.map(x=><option key={x}>{x}</option>)}</select></label><label>Topic<select value={c.topic} onChange={e=>field('topic',e.target.value)}><option value="">All topics</option>{c.topic&&!topics.includes(c.topic)&&<option>{c.topic}</option>}{topics.map(x=><option key={x}>{x}</option>)}</select></label></div>
 <details className="quiz-type-options"><summary>Question types <span>{c.types.length?`${c.types.length} selected`:'All types'}</span></summary><div className="quiz-type-chips">{questionTypes.map(([id,label])=><label key={id}><input type="checkbox" checked={c.types.includes(id)} onChange={e=>field('types',e.target.checked?[...c.types,id]:c.types.filter(x=>x!==id))}/><span>{label}</span></label>)}</div><small>No types selected includes all types.</small></details></section>
 <section className="quiz-config-card"><div className="quiz-config-heading"><Shuffle size={19}/><div><h2>Practice</h2><p>Choose what to review and how it appears.</p></div></div><div className="quiz-mode-options" role="group" aria-label="Review mode">{[['daily','Daily'],['due','Due'],['all','All questions']].map(([id,label])=><button key={id} aria-pressed={c.mode===id} onClick={()=>field('mode',id)}>{label}</button>)}</div><p className="quiz-mode-help">{c.mode==='daily'?'Today’s due questions, with your chosen filters.':c.mode==='due'?'Questions ready for their next review.':'Practice regardless of the next review date.'}</p><label>Practice focus<select value={c.focus} onChange={e=>field('focus',e.target.value)}><option value="all">Everything</option><option value="weak">Weak questions</option><option value="mistakes">Previous mistakes</option></select></label><label className="quiz-shuffle-toggle"><span><strong>Shuffle question order</strong><small>A fresh order each time you start.</small></span><input type="checkbox" checked={c.shuffle} onChange={e=>field('shuffle',e.target.checked)}/></label></section>
 <footer className="quiz-config-footer"><div><strong>{q.length} {q.length===1?'question':'questions'}</strong><p>{q.length?'Ready with your current choices.':'Nothing matches. Change the filters or review mode.'}</p></div><Button disabled={!q.length} onClick={()=>onStart(filterQuiz(items,reports,c),c.mode)}>Start quiz</Button></footer>
 </div>;
}
async function imageFile(file:File){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024)throw new Error('Choose a PNG, JPEG or WebP image under 2 MB.');return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});}
export function ExtendedEditor({draft,setDraft}:any){const [error,setError]=useState('');async function upload(file:File,key?:string){try{const image=await imageFile(file);setDraft(d=>key?{...d,optionImages:{...d.optionImages,[key]:image}}:{...d,image});setError('');}catch(e:any){setError(e.message);}}return <div className="extended-editor">{['matching','ordering','cloze','fill_blank_options'].includes(draft.type)&&<label>{draft.type==='matching'?'Matching pairs — left | right, one pair per line':draft.type==='ordering'?'Sequence steps — correct order, one per line':'Blank answers — one per ___ marker, in order'}<textarea value={draft.structured||''} onChange={e=>setDraft(d=>({...d,structured:e.target.value}))}/></label>}<label>Accepted alternative answers — one per line<textarea value={draft.accepted||''} onChange={e=>setDraft(d=>({...d,accepted:e.target.value}))}/></label><label className="learning-check"><input type="checkbox" checked={draft.fuzzy!==false} onChange={e=>setDraft(d=>({...d,fuzzy:e.target.checked}))}/>Accept one-character typos in words of 5+ letters</label><label>Tags — comma separated<input value={draft.tags||''} onChange={e=>setDraft(d=>({...d,tags:e.target.value}))}/></label><label>Question image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label>{draft.image&&<><img className="question-media" src={draft.image} alt="Question preview"/><Button variant="outline" onClick={()=>setDraft(d=>({...d,image:undefined}))}>Remove question image</Button></>}{['single_choice','multi_select'].includes(draft.type)&&draft.options.split('\n').filter(Boolean).map(choice=><label key={choice}>Image for {choice}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],choice)}/>{draft.optionImages?.[choice]&&<><img className="choice-media" src={draft.optionImages[choice]} alt={choice}/><button onClick={()=>setDraft(d=>({...d,optionImages:Object.fromEntries(Object.entries(d.optionImages).filter(([k])=>k!==choice))}))}>Remove image</button></>}</label>)}<p role="status">{error}</p></div>;}
export function StructuredAnswer({item,value,onChange,disabled,onGrade}:any){if(item.type==='matching')return <MatchingAnswer key={item.id} item={item} value={value} onChange={onChange} disabled={disabled} onGrade={onGrade}/>;const values=value.length?value:item.type==='ordering'?[...item.sequence].reverse():Array(item.type==='matching'?item.pairs.length:item.blanks.length).fill('');function change(i:number,v:string){const copy=[...values];copy[i]=v;onChange(copy);}return <div className="structured-answer">{item.type==='matching'?item.pairs.map((p,i)=><label key={p.left}>{p.left}<select aria-label={`Match ${p.left}`} disabled={disabled} value={values[i]||''} onChange={e=>change(i,e.target.value)}><option value="">Choose a match</option>{[...item.pairs].reverse().map(p=><option key={p.right}>{p.right}</option>)}</select></label>):item.type==='cloze'?item.blanks.map((_,i)=><label key={i}>Blank {i+1}<input aria-label={`Blank ${i+1}`} disabled={disabled} value={values[i]||''} onChange={e=>change(i,e.target.value)}/></label>):values.map((step,i)=><div className="sequence-step" key={step}><span>{i+1}. {step}</span><button aria-label={`Move ${step} up`} disabled={disabled||i===0} onClick={()=>{const x=[...values];[x[i-1],x[i]]=[x[i],x[i-1]];onChange(x);}}>↑</button><button aria-label={`Move ${step} down`} disabled={disabled||i===values.length-1} onClick={()=>{const x=[...values];[x[i+1],x[i]]=[x[i],x[i+1]];onChange(x);}}>↓</button></div>)}{!disabled&&<Button disabled={values.some(x=>!x)} onClick={()=>onGrade(values)}>Check answer</Button>}</div>;}
export function AnalyticsPanel({reports}:any){const a=analytics(reports);return <section className="learning-panel"><h2>Learning insights</h2>{!a.total?<p>Finish a quiz to see your strengths and weaknesses.</p>:<>{Object.entries(a.groups).map(([key,groups]:any)=><div key={key}><h3>Accuracy by {key}</h3><div className="analytics-rows">{Object.entries(groups).sort(([,a]:any,[,b]:any)=>a.correct/a.total-b.correct/b.total).map(([name,s]:any)=><div key={name}><span>{key==='type'?typeLabel(name):name}</span><strong>{Math.round(s.correct/s.total*100)}%</strong><small>{s.total} attempts · {(s.seconds/s.total).toFixed(1)}s average</small><progress max={s.total} value={s.correct}/></div>)}</div></div>)}<h3>Accuracy trend</h3><div className="trend-bars">{a.trend.map(r=><div key={r.id} title={`${r.date}: ${r.accuracy}%`}><span>{r.accuracy}%</span><progress max="100" value={r.accuracy}/><small>{new Date(r.date).toLocaleDateString()}</small></div>)}</div><h3>Repeated mistakes</h3>{a.mistakes.filter(x=>x.count>1).slice(0,10).map(x=><p key={x.prompt}>{x.prompt} <strong>· {x.count} misses</strong></p>)}{!a.mistakes.some(x=>x.count>1)&&<p>No repeated mistakes yet.</p>}</>}</section>;}
export function BackupRestore(){const [text,setText]=useState(''),[data,setData]=useState<any>(null),[status,setStatus]=useState('');function review(){try{setData(validateBackup(JSON.parse(text),validateQuestion));setStatus('Backup validated. Download your current backup before replacing it.');}catch(e:any){setData(null);setStatus(e.message);}}return <section className="learning-panel"><h2>Restore local backup</h2><p>Replace study data and settings with a full RecallFlow backup.</p><label>Backup file<input type="file" accept="application/json,.json" onChange={async e=>{if(e.target.files?.[0]){setText(await e.target.files[0].text());setData(null);}}}/></label><label>Or paste backup JSON<textarea value={text} onChange={e=>{setText(e.target.value);setData(null);}}/></label><Button variant="outline" disabled={!text.trim()} onClick={review}>Review backup</Button>{data&&<div className="settings-confirm"><p>Replace with {data.questions.length} questions, {data.reports.length} reports and {data.streakDays.length} activity days?</p><Button onClick={()=>{try{restoreBackup(data);location.reload();}catch(e:any){setStatus('Restore failed; original data was retained. '+e.message);}}}>Confirm restore backup</Button><Button variant="outline" onClick={()=>setData(null)}>Cancel restore</Button></div>}<p role="status">{status}</p></section>;}
export function OfflineSettings(){const [ready,setReady]=useState(false),[install,setInstall]=useState<any>(null);useEffect(()=>{let active=true;const check=()=>{if(active)setReady(!!navigator.serviceWorker?.controller);};check();navigator.serviceWorker?.addEventListener('controllerchange',check);navigator.serviceWorker?.ready.then(check);const prompt=(e:any)=>{e.preventDefault();setInstall(e);};window.addEventListener('beforeinstallprompt',prompt);return()=>{active=false;navigator.serviceWorker?.removeEventListener('controllerchange',check);window.removeEventListener('beforeinstallprompt',prompt);};},[]);return <section className="learning-panel"><h2>Install &amp; offline</h2><p role="status">{ready?'Offline study is ready on this browser.':'Preparing offline study…'}</p><p>Questions, images, progress and reports stay on this device. Open RecallFlow online once before studying offline.</p>{install?<Button onClick={async()=>{await install.prompt();setInstall(null);}}>Install RecallFlow</Button>:<small>Use your browser’s Install app or Add to Home Screen option when available.</small>}</section>;}
