import React,{useState,useRef} from 'react';
import {Plus,Trash2,ArrowUp,ArrowDown,Check,Save,LoaderCircle,ImagePlus,Eye,Volume2,BookOpen} from 'lucide-react';
import {questionTypes,typeLabel,gradeQuestion} from '../question-types.js';
import {Button} from './components/Button';
import {SpeechButton} from './KokoroPanel';
const help:any={short_answer:'Ask a direct question and write the answer you expect.',fill_blank:'Use ___ where the missing answer belongs.',single_choice:'Add choices, then select the one correct answer.',flashcard:'Write the front of the card and the answer on the back.',true_false:'Write a statement and choose whether it is true or false.',multi_select:'Add choices and mark every correct answer.',numeric:'Set the expected number and how much variation to accept.',matching:'Each row is a pair. Learners will connect the two sides.',ordering:'Write the steps in their correct order. The quiz will mix them up.',cloze:'Use ___ for each gap, then enter its answer below.',fill_blank_options:'Create gaps with ___ and give learners a word bank.'};
function ImageUpload({label,image,onPick,onRemove}:any){
 const input=useRef<HTMLInputElement>(null),[loading,setLoading]=useState(false);
 return <div className="editor-image-upload"><div className={`editor-upload-preview ${image?'has-image':''}`}>
 {image?<img src={image} alt={`${label} preview`}/>:<><ImagePlus size={31}/><span>No image added</span></>}
 </div><div className="editor-upload-bottom"><div><strong>{label}</strong><small>PNG, JPEG or WebP · up to 2 MB</small></div><button type="button" className="editor-upload-choose" disabled={loading} aria-label={`${image?'Change':'Choose'} ${label.toLowerCase()}`} onClick={()=>input.current?.click()}>{loading?<LoaderCircle size={15} className="speech-spinner"/>:null}{loading?'Adding…':image?'Change image':'Choose image'}</button></div>
 {image&&<button type="button" className="editor-upload-remove" aria-label={`Remove ${label.toLowerCase()}`} disabled={loading} onClick={onRemove}><Trash2 size={14}/>Remove image</button>}
 <input ref={input} type="file" aria-label={`Upload ${label.toLowerCase()}`} accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';if(file){setLoading(true);try{await onPick(file);}finally{setLoading(false);}}}}/>
 </div>;
}
function FlashcardEditorPreview({draft}:any){
 const [showBack,setShowBack]=useState(false);
 return <div className="editor-question-preview"><small>Flashcard preview · tap to flip</small>{draft.image&&<img src={draft.image} alt="Flashcard image"/>}<button type="button" className="editor-flashcard-preview" aria-pressed={showBack} aria-label={showBack?'Show flashcard front':'Show flashcard back'} onClick={()=>setShowBack(value=>!value)}><span className={`editor-flashcard-preview-inner${showBack?' is-back':''}`}><span className="editor-flashcard-preview-face editor-flashcard-front"><small>FRONT · QUESTION</small><strong>{draft.prompt||'Your question appears here'}</strong><em>Tap to reveal the answer</em></span><span className="editor-flashcard-preview-face editor-flashcard-back"><small>BACK · ANSWER</small><strong>{draft.answer||'Your answer appears here'}</strong><em>Tap to see the question</em></span></span></button><small>Preview only · the quiz card flips the same way.</small></div>;
}

function QuestionTypePreview({draft,choices,pairs,steps}:any){
 const type=draft.type,blanks=String(draft.structured||'').split('\n').map((x:string)=>x.trim()).filter(Boolean),options=type==='true_false'?['True','False']:choices.filter(Boolean),answerList=String(draft.answer||'').split('\n').filter(Boolean);
 const item={...draft,answer:draft.answer||'',options,correctAnswers:type==='multi_select'?answerList:undefined,acceptedAnswers:String(draft.accepted||'').split('\n').filter(Boolean),fuzzy:draft.fuzzy!==false,numericTolerance:Number(draft.numericTolerance||0),pairs:pairs.map((p:string[])=>({left:p[0],right:p[1]})),sequence:steps.filter(Boolean),blanks};
 const initial=type==='ordering'?[...steps.filter(Boolean)].reverse():['cloze','fill_blank_options'].includes(type)?Array(blanks.length).fill(''):type==='multi_select'?[]:type==='matching'?Array(pairs.length).fill(''):'';
 const [value,setValue]=useState<any>(initial),[revealed,setRevealed]=useState(false),[showBack,setShowBack]=useState(false);
 React.useEffect(()=>{setValue(type==='ordering'?[...steps.filter(Boolean)].reverse():['cloze','fill_blank_options'].includes(type)?Array(blanks.length).fill(''):type==='multi_select'?[]:type==='matching'?Array(pairs.length).fill(''):'');setRevealed(false);setShowBack(false);},[type,draft.prompt,draft.answer,draft.options,draft.structured]);
 const complete=type==='multi_select'?value.length>0:['cloze','fill_blank_options','matching','ordering'].includes(type)?Array.isArray(value)&&value.length>0&&value.every(Boolean):String(value).trim().length>0;
 const correct=()=>{try{return gradeQuestion(item,value);}catch{return false;}};
 const updateAt=(i:number,next:string)=>setValue((old:any)=>{const copy=Array.isArray(old)?[...old]:[];copy[i]=next;return copy;});
 const check=<button type="button" className="editor-preview-check" disabled={!complete||revealed} onClick={()=>setRevealed(true)}>{revealed?(correct()?'Correct':'Show answer'):'Check answer'}</button>;
 if(type==='flashcard')return <FlashcardEditorPreview draft={draft}/>;
 return <div className="editor-question-preview"><small>{typeLabel(type)} · interactive preview</small>{draft.image&&<img src={draft.image} alt="Question preview"/>}<h3>{draft.prompt||'Your question appears here'}</h3>
 {['single_choice','true_false','multi_select'].includes(type)&&<div className="editor-preview-options">{options.map((x:string,i:number)=>{const picked=type==='multi_select'?value.includes(x):value===x,isCorrect=type==='multi_select'?answerList.includes(x):draft.answer===x;return <button type="button" key={i} className={`editor-preview-option${picked?' is-selected':''}${revealed&&isCorrect?' is-correct':''}${revealed&&picked&&!isCorrect?' is-wrong':''}`} aria-pressed={picked} onClick={()=>!revealed&&setValue((old:any)=>type==='multi_select'?(old.includes(x)?old.filter((v:string)=>v!==x):[...old,x]):x)}>{draft.optionImages?.[x]&&<img src={draft.optionImages[x]} alt=""/>}<span>{String.fromCharCode(65+i)} · {x}</span></button>})}{check}</div>}
 {type==='fill_blank'&&<div className="editor-preview-interaction"><p className="editor-preview-sentence">{draft.prompt.split(/_{2,}/g).map((part:string,i:number)=><React.Fragment key={i}>{part}{i<draft.prompt.split(/_{2,}/g).length-1&&<input aria-label="Answer the blank" value={value} disabled={revealed} onChange={e=>setValue(e.target.value)} placeholder="…"/>}</React.Fragment>)}</p>{check}{revealed&&<small className={correct()?'is-correct-text':'is-wrong-text'}>Answer: {draft.answer||'Add the answer above'}</small>}</div>}
 {type==='numeric'&&<div className="editor-preview-interaction"><label className="editor-preview-answer-label">Your answer<input aria-label="Preview numeric answer" inputMode="decimal" value={value} disabled={revealed} onChange={e=>setValue(e.target.value)} placeholder="Enter a number…"/></label>{check}{revealed&&<small className={correct()?'is-correct-text':'is-wrong-text'}>Answer: {draft.answer||'Add the answer above'}{Number(draft.numericTolerance)>0?` (±${draft.numericTolerance})`:''}</small>}</div>}
 {type==='short_answer'&&<div className="editor-preview-interaction"><label className="editor-preview-answer-label">Your answer<textarea aria-label="Preview short answer" value={value} disabled={revealed} onChange={e=>setValue(e.target.value)} placeholder="Write what you remember…"/></label>{check}{revealed&&<small className={correct()?'is-correct-text':'is-wrong-text'}>Answer: {draft.answer||'Add the answer above'}</small>}</div>}
 {['cloze','fill_blank_options'].includes(type)&&<div className="editor-preview-interaction"><p className="editor-preview-sentence">{draft.prompt.split(/_{2,}/g).map((part:string,i:number)=><React.Fragment key={i}>{part}{i<draft.prompt.split(/_{2,}/g).length-1&&(type==='cloze'?<input aria-label={`Blank ${i+1}`} value={value[i]||''} disabled={revealed} onChange={e=>updateAt(i,e.target.value)}/>:<button type="button" className="editor-preview-gap" aria-label={`Blank ${i+1}`} disabled={revealed} onClick={()=>setValue((old:any)=>{const n=[...old];n[i]=n[i]?'':options.find((o:string)=>!old.includes(o))||options[0]||'';return n;})}>{value[i]||`Blank ${i+1}`}</button>)}</React.Fragment>)}</p>{type==='fill_blank_options'&&<div className="editor-preview-options">{options.map((x:string,i:number)=><button type="button" className={`editor-preview-option${value.includes(x)?' is-selected':''}`} key={i} disabled={revealed} onClick={()=>{const empty=value.findIndex((v:string)=>!v);if(empty>=0)updateAt(empty,x);}}>{x}</button>)}</div>}{check}{revealed&&<small className={correct()?'is-correct-text':'is-wrong-text'}>Answer: {blanks.join(' · ')||'Add a blank answer above'}</small>}</div>}
 {type==='matching'&&<div className="editor-preview-interaction">{pairs.map((pair:string[],i:number)=><label className="editor-preview-match" key={i}><span>{pair[0]||'Left side'}</span><select aria-label={`Match ${pair[0]||i+1}`} value={value[i]||''} disabled={revealed} onChange={e=>updateAt(i,e.target.value)}><option value="">Choose a match</option>{pairs.map((p:string[],j:number)=><option key={j} value={p[1]}>{p[1]||'Matching answer'}</option>)}</select></label>)}{check}{revealed&&<small className={correct()?'is-correct-text':'is-wrong-text'}>Matches: {pairs.map((p:string[])=>`${p[0]} → ${p[1]}`).join(' · ')}</small>}</div>}
 {type==='ordering'&&<div className="editor-preview-interaction editor-preview-order">{value.map((x:string,i:number)=><div className="editor-preview-option" key={`${i}-${x}`}><span>{i+1} · {x||'Step'}</span><div><button type="button" aria-label="Move step up" disabled={revealed||i===0} onClick={()=>setValue((old:string[])=>{const n=[...old];[n[i-1],n[i]]=[n[i],n[i-1]];return n;})}>↑</button><button type="button" aria-label="Move step down" disabled={revealed||i===value.length-1} onClick={()=>setValue((old:string[])=>{const n=[...old];[n[i+1],n[i]]=[n[i],n[i+1]];return n;})}>↓</button></div></div>)}{check}{revealed&&<small className={correct()?'is-correct-text':'is-wrong-text'}>Correct order: {steps.filter(Boolean).join(' → ')}</small>}</div>}
 <small>Preview only · your answers here are not saved.</small></div>;
}

export function QuestionEditor({draft,setDraft,onSave,onCancel,busy,status,saved,editing,prepareAudio,setPrepareAudio,onAnother}:any){
 const [preview,setPreview]=useState(false),[mediaError,setMediaError]=useState(''),[step,setStep]=useState(0);
 const tabs=useRef<HTMLDivElement>(null);
 const tabLabels=['Question','Images','Optional'];
 function goStep(next:number){setStep(next);tabs.current?.scrollIntoView({block:'start',behavior:'smooth'});}
 function tabKey(e:React.KeyboardEvent,index:number){let next=index;if(e.key==='ArrowRight')next=(index+1)%tabLabels.length;else if(e.key==='ArrowLeft')next=(index+tabLabels.length-1)%tabLabels.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabLabels.length-1;else return;e.preventDefault();goStep(next);(tabs.current?.querySelectorAll('button')[next] as HTMLButtonElement)?.focus();}
 const field=(key:string,value:any)=>setDraft((d:any)=>({...d,[key]:value}));
 const lines=(key:string,min=0)=>{const rows=String(draft[key]||'').split('\n');while(rows.length<min)rows.push('');return rows;};
 const update=(key:string,i:number,value:string,min=0)=>{const rows=lines(key,min);rows[i]=value;field(key,rows.join('\n'));};
 const choices=lines('options',2),steps=lines('structured',2),blankCount=(draft.prompt.match(/_{2,}/g)||[]).length;
 const pairs=steps.map((line:string)=>{const [left='',...rest]=line.split('|');return [left,rest.join('|')];});
 const markChoice=(choice:string,on:boolean)=>{if(draft.type==='single_choice')field('answer',choice);else{const answers=lines('answer').filter(Boolean);field('answer',(on?[...new Set([...answers,choice])]:answers.filter((x:string)=>x!==choice)).join('\n'));}};
 function choiceChange(i:number,value:string){const old=choices[i],next=[...choices];next[i]=value;setDraft((d:any)=>({...d,options:next.join('\n'),answer:d.type==='single_choice'?(d.answer===old?value:d.answer):String(d.answer).split('\n').map((x:string)=>x===old?value:x).join('\n'),optionImages:old&&d.optionImages?.[old]?{...d.optionImages,[old]:undefined,[value]:d.optionImages[old]}:d.optionImages}));}
 function removeChoice(i:number){const old=choices[i];setDraft((d:any)=>({...d,options:choices.filter((_:string,j:number)=>j!==i).join('\n'),answer:d.type==='single_choice'?(d.answer===old?'':d.answer):String(d.answer).split('\n').filter((x:string)=>x!==old).join('\n'),optionImages:Object.fromEntries(Object.entries(d.optionImages||{}).filter(([k])=>k!==old&&d.optionImages[k]))}));}
 async function upload(file:File,key?:string){try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024)throw new Error('Choose a PNG, JPEG or WebP image under 2 MB.');const image=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('Could not read this image.'));r.readAsDataURL(file);});setDraft((d:any)=>key?{...d,optionImages:{...d.optionImages,[key]:image}}:{...d,image});setMediaError('');}catch(e:any){setMediaError(e.message);}}
 if(saved)return <section className="editor-success" role="status"><span className="editor-success-icon"><Check size={30}/></span><h2>{editing?'Question updated':'Question created'}</h2><p>{status}</p><div className="editor-saved-question"><small>{typeLabel(saved.type)}</small><strong>{saved.prompt}</strong><SpeechButton questionId={saved.id} text={saved.prompt} spokenText={saved.type==='fill_blank'?saved.prompt.replace(/_{2,}/g,'blank'):undefined} label="Play saved question audio"/></div><Button onClick={onCancel}>Back to question bank</Button><Button variant="outline" onClick={()=>{setStep(0);setPreview(false);setMediaError('');onAnother();}}><Plus size={16}/>Add another question</Button></section>;
 return <div className="editor-composer" aria-busy={busy}>
 <fieldset disabled={busy} className="editor-fields">
 <div className="editor-tabs editor-numbered-steps" ref={tabs} role="tablist" aria-label="Question editor sections">{tabLabels.map((label,i)=><button type="button" key={label} role="tab" id={`editor-tab-${i}`} aria-selected={step===i} aria-controls={`editor-panel-${i}`} tabIndex={step===i?0:-1} onClick={()=>goStep(i)} onKeyDown={e=>tabKey(e,i)}><span>{i+1}</span>{label}</button>)}</div>
 <section className="editor-section editor-step-panel" role="tabpanel" id="editor-panel-0" aria-labelledby="editor-tab-0" hidden={step!==0}><label>Question type<select value={draft.type} onChange={e=>{field('type',e.target.value);setPreview(false);}}>{questionTypes.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><p className="editor-type-help">{help[draft.type]}</p><label>{draft.type==='flashcard'?'Front of card':'Question prompt'}<textarea value={draft.prompt} onChange={e=>field('prompt',e.target.value)} placeholder={['fill_blank','cloze','fill_blank_options'].includes(draft.type)?'The capital of France is ___.':draft.type==='matching'?'Match each country to its capital.':'What would you like to remember?'}/></label>{['fill_blank','cloze','fill_blank_options'].includes(draft.type)&&<button type="button" className="editor-text-button" onClick={()=>field('prompt',draft.prompt+' ___')}><Plus size={14}/>Insert a blank</button>}
 <div className="editor-answer-fields">
 {['short_answer','fill_blank','flashcard','numeric'].includes(draft.type)&&<label>{draft.type==='flashcard'?'Back of card':'Correct answer'}<textarea value={draft.answer} onChange={e=>field('answer',e.target.value)} placeholder={draft.type==='numeric'?'e.g. 3.14':'Enter the correct answer'}/></label>}
 {draft.type==='numeric'&&<label>Accepted tolerance (±)<input inputMode="decimal" value={draft.numericTolerance} onChange={e=>field('numericTolerance',e.target.value)}/><small>0 means exact. For example, 3.14 ± 0.01.</small></label>}
 {draft.type==='true_false'&&<div className="editor-boolean" role="group" aria-label="Correct answer">{['True','False'].map(x=><button type="button" key={x} aria-pressed={draft.answer===x} onClick={()=>field('answer',x)}>{draft.answer===x&&<Check size={17}/>} {x}</button>)}</div>}
 {['single_choice','multi_select','fill_blank_options'].includes(draft.type)&&<div className="editor-choice-list"><p className="editor-list-label">{draft.type==='fill_blank_options'?'Word bank':'Answer choices'}<small>{draft.type==='multi_select'?'Mark all correct choices':draft.type==='single_choice'?'Mark the correct choice':'Include the answers and optional distractors'}</small></p>{choices.map((choice:string,i:number)=><div className="editor-choice-row" key={i}>{draft.type!=='fill_blank_options'?<input type={draft.type==='single_choice'?'radio':'checkbox'} name="editor-correct-choice" aria-label={`Choice ${i+1} is correct`} checked={!!choice&&(draft.type==='single_choice'?draft.answer===choice:lines('answer').includes(choice))} onChange={e=>markChoice(choice,e.target.checked)} disabled={!choice||busy}/>:<span className="editor-row-number">{i+1}</span>}<input aria-label={`Choice ${i+1}`} value={choice} placeholder={`Choice ${i+1}`} onChange={e=>choiceChange(i,e.target.value)}/><button type="button" aria-label={`Remove choice ${i+1}`} disabled={choices.length<=2} onClick={()=>removeChoice(i)}><Trash2 size={16}/></button></div>)}<button type="button" className="editor-text-button" onClick={()=>field('options',choices.concat('').join('\n'))}><Plus size={15}/>Add choice</button></div>}
 {draft.type==='matching'&&<div className="editor-pairs"><div className="editor-pair-labels"><span>Left side</span><span>Matching answer</span></div>{pairs.map((pair:string[],i:number)=><div className="editor-pair-row" key={i}><input aria-label={`Pair ${i+1} left`} value={pair[0]} placeholder="e.g. Japan" onChange={e=>update('structured',i,e.target.value+'|'+pair[1],2)}/><span>↔</span><input aria-label={`Pair ${i+1} right`} value={pair[1]} placeholder="e.g. Tokyo" onChange={e=>update('structured',i,pair[0]+'|'+e.target.value,2)}/><button type="button" aria-label={`Remove pair ${i+1}`} disabled={pairs.length<=2} onClick={()=>field('structured',steps.filter((_:string,j:number)=>i!==j).join('\n'))}><Trash2 size={15}/></button></div>)}<button type="button" className="editor-text-button" onClick={()=>field('structured',steps.concat('').join('\n'))}><Plus size={15}/>Add pair</button></div>}
 {draft.type==='ordering'&&<div className="editor-sequence">{steps.map((step:string,i:number)=><div className="editor-step-row" key={i}><span className="editor-row-number">{i+1}</span><input aria-label={`Step ${i+1}`} value={step} placeholder={`Step ${i+1}`} onChange={e=>update('structured',i,e.target.value,2)}/><div><button type="button" aria-label={`Move step ${i+1} up`} disabled={i===0} onClick={()=>{const next=[...steps];[next[i-1],next[i]]=[next[i],next[i-1]];field('structured',next.join('\n'));}}><ArrowUp size={14}/></button><button type="button" aria-label={`Move step ${i+1} down`} disabled={i===steps.length-1} onClick={()=>{const next=[...steps];[next[i+1],next[i]]=[next[i],next[i+1]];field('structured',next.join('\n'));}}><ArrowDown size={14}/></button><button type="button" aria-label={`Remove step ${i+1}`} disabled={steps.length<=2} onClick={()=>field('structured',steps.filter((_:string,j:number)=>i!==j).join('\n'))}><Trash2 size={14}/></button></div></div>)}<button type="button" className="editor-text-button" onClick={()=>field('structured',steps.concat('').join('\n'))}><Plus size={15}/>Add step</button></div>}
 {['cloze','fill_blank_options'].includes(draft.type)&&<div className="editor-blanks"><p className="editor-list-label">Blank answers<small>{blankCount?`${blankCount} ${blankCount===1?'gap':'gaps'} in your prompt`:'Add ___ to your question to create a gap'}</small></p>{Array.from({length:blankCount},(_,i)=><label key={i}>Blank {i+1}<input value={lines('structured')[i]||''} onChange={e=>update('structured',i,e.target.value,blankCount)} placeholder="Correct word or phrase"/></label>)}</div>}
 {['short_answer','fill_blank','cloze'].includes(draft.type)&&<details className="editor-details"><summary>Grading options</summary>{draft.type!=='cloze'&&<label>Accepted alternative answers<textarea value={draft.accepted||''} onChange={e=>field('accepted',e.target.value)} placeholder="One accepted answer per line"/></label>}{draft.type!=='numeric'&&<label className="editor-toggle"><input type="checkbox" checked={draft.fuzzy!==false} onChange={e=>field('fuzzy',e.target.checked)}/><span>Accept minor typos<small>One-character typos in words of 5+ letters.</small></span></label>}</details>}
 </div></section>
 <section className="editor-section editor-step-panel" role="tabpanel" id="editor-panel-1" aria-labelledby="editor-tab-1" hidden={step!==1}><div className="editor-section-heading"><span><ImagePlus size={18}/></span><div><h2>Image attachments</h2><p>Optional. Add a prompt image or images for answer choices.</p></div></div><ImageUpload label="Question image" image={draft.image} onPick={(file:File)=>upload(file)} onRemove={()=>field('image',undefined)}/>{['single_choice','multi_select'].includes(draft.type)&&choices.filter(Boolean).map((choice:string)=><ImageUpload key={choice} label={`Image for ${choice}`} image={draft.optionImages?.[choice]} onPick={(file:File)=>upload(file,choice)} onRemove={()=>field('optionImages',Object.fromEntries(Object.entries(draft.optionImages||{}).filter(([key])=>key!==choice)))}/>)}{mediaError&&<p role="alert">{mediaError}</p>}{!['single_choice','multi_select'].includes(draft.type)&&<p className="editor-image-note">Every question type supports a prompt image. Answer-choice images are available for Multiple choice and Multi-select.</p>}</section>
 <section className="editor-section editor-ready editor-step-panel" role="tabpanel" id="editor-panel-2" aria-labelledby="editor-tab-2" hidden={step!==2}><div className="editor-section-heading"><span>03</span><div><h2>Optional settings</h2><p>You can save without adding anything here.</p></div></div><details className="editor-details editor-organization"><summary>Organize question <small>Subject, topic & tags</small></summary><div className="editor-meta-grid"><label>Subject<input value={draft.subject} onChange={e=>field('subject',e.target.value)} placeholder="e.g. Geography"/></label><label>Topic<input value={draft.topic} onChange={e=>field('topic',e.target.value)} placeholder="e.g. Capitals"/></label></div><label>Tags<input value={draft.tags||''} onChange={e=>field('tags',e.target.value)} placeholder="e.g. revision, chapter 1"/><small>Separate tags with commas.</small></label></details><label className="editor-toggle"><input type="checkbox" checked={prepareAudio} onChange={e=>setPrepareAudio(e.target.checked)}/><span><Volume2 size={16}/>Prepare voice when saving<small>Save question and answer audio using your saved voice. First use can take longer.</small></span></label><button type="button" className="editor-text-button" aria-expanded={preview} onClick={()=>setPreview(!preview)}><Eye size={16}/>{preview?'Hide preview':'Preview question'}</button>{preview&&<QuestionTypePreview draft={draft} choices={choices} pairs={pairs} steps={steps}/> }</section>
 </fieldset>
 {status&&<p className="editor-save-message" role={busy?'status':'alert'} aria-live="polite">{busy&&<LoaderCircle size={17} className="speech-spinner"/>}{status}</p>}
 <footer className="question-editor-actions editor-tab-actions"><div className="editor-step-controls"><Button variant="outline" onClick={()=>step===0?onCancel():goStep(step-1)} disabled={busy}>{step===0?'Cancel':'Back'}</Button><Button variant="outline" onClick={()=>goStep(step+1)} disabled={busy||step===tabLabels.length-1}>Next</Button></div><Button onClick={onSave} disabled={busy}>{busy?<LoaderCircle size={16} className="speech-spinner"/>:<Save size={16}/>} {busy?'Saving…':editing?'Save changes':'Create question'}</Button></footer>
 </div>;
}
