import React,{useEffect,useRef,useState} from 'react';
import {Button} from './components/Button';
import {textGrade} from '../learning-core.js';
export function MatchingAnswer({item,value,onChange,disabled,onGrade}:any){
 const [active,setActive]=useState<number|null>(null),[message,setMessage]=useState(''),[lines,setLines]=useState<any[]>([]);
 const board=useRef<HTMLDivElement>(null),values=item.pairs.map((_,i)=>value[i]||''),rights=[...item.pairs].reverse();
 useEffect(()=>{const el=board.current;if(!el)return;function measure(){const area=el!.getBoundingClientRect();setLines(values.flatMap((v,i)=>{if(!v)return [];const a=el!.querySelector(`[data-left="${i}"]`)?.getBoundingClientRect(),j=rights.findIndex(p=>p.right===v),b=el!.querySelector(`[data-right="${j}"]`)?.getBoundingClientRect();return a&&b?[{i,x1:a.right-area.left,y1:a.top+a.height/2-area.top,x2:b.left-area.left,y2:b.top+b.height/2-area.top}]:[];}));}measure();const observer=new ResizeObserver(measure);observer.observe(el);return()=>observer.disconnect();},[item,value]);
 function connect(right:string){if(active===null){const owner=values.indexOf(right);if(owner>=0)setActive(owner);else setMessage('Tap a word on the left first.');return;}const next=values.map((v,i)=>i===active?right:v===right?'':v);onChange(next);setActive(null);setMessage('');}
 const state=(i:number)=>disabled?(values[i]===item.pairs[i].right?'correct':'wrong'):active===i?'active':values[i]?'paired':'idle';
 return <div className="structured-answer matching-answer"><p className="split-answer-help">Tap a word on the left, then its match on the right.</p><div className="matching-board" ref={board}><svg className="match-connections" aria-hidden="true">{lines.map(l=><path key={l.i} data-state={state(l.i)} d={`M ${l.x1} ${l.y1} C ${(l.x1+l.x2)/2} ${l.y1}, ${(l.x1+l.x2)/2} ${l.y2}, ${l.x2} ${l.y2}`}/>)}</svg><div className="match-column" aria-label="Items to match">{item.pairs.map((p,i)=><button key={p.left} data-left={i} data-state={state(i)} aria-label={`Select ${p.left}`} aria-pressed={active===i} disabled={disabled} onClick={()=>{setActive(i);setMessage('');}}><span>{p.left}</span>{values[i]&&<b>{i+1}</b>}</button>)}</div><div className="match-column" aria-label="Possible matches">{rights.map((p,j)=>{const owner=values.indexOf(p.right);return <button key={p.right} data-right={j} data-state={owner<0?'idle':state(owner)} aria-label={`Match with ${p.right}`} aria-pressed={owner>=0} disabled={disabled} onClick={()=>connect(p.right)}>{owner>=0&&<b>{owner+1}</b>}<span>{p.right}</span></button>;})}</div></div><div className="matching-tools"><p role="status">{message||`${values.filter(Boolean).length} of ${values.length} pairs connected`}</p>{!disabled&&<button onClick={()=>{onChange([]);setActive(null);setMessage('');}}>Reset matches</button>}</div>{!disabled&&<Button disabled={values.some(x=>!x)} onClick={()=>onGrade(values)}>Check matches</Button>}</div>;
}
export function InlineBlankAnswer({item,value,onChange,disabled,onGrade}:any){
 const multi=item.type==='cloze',values=multi?item.blanks.map((_,i)=>value[i]||''):[value||''];const parts=item.prompt.split(/_{2,}/g),complete=values.every(v=>v.trim());
 function field(index:number){const i=multi?index:0;return <input key={'blank-'+index} aria-label={`Blank ${index+1}`} autoComplete="off" spellCheck={false} value={values[i]} disabled={disabled} placeholder="" data-state={disabled?(textGrade({answer:multi?item.blanks[i]:item.answer,acceptedAnswers:multi?[]:item.acceptedAnswers,fuzzy:item.fuzzy},values[i])==='wrong'?'wrong':'correct'):'idle'} onChange={e=>{if(multi){const next=[...values];next[i]=e.target.value;onChange(next);}else onChange(e.target.value);}} onKeyDown={e=>{if(e.key==='Enter'&&complete&&!disabled)onGrade(multi?values:values[0]);}}/>;}
 return <div className="inline-blank-answer"><p className="blank-sentence">{parts.length>1?parts.map((part,i)=><React.Fragment key={i}>{part}{i<parts.length-1&&field(i)}</React.Fragment>):<>{item.prompt} {field(0)}</>}</p><p className="split-answer-help">Type directly into {multi?'each gap':'the gap'} to complete the sentence.</p>{!disabled&&<Button className="split-submit" disabled={!complete} onClick={()=>onGrade(multi?values:values[0])}>Check {multi?'answers':'answer'}</Button>}</div>;
}

export function WordBankAnswer({item,value,onChange,disabled,onGrade}:any){
 const [active,setActive]=useState(0),values=item.blanks.map((_,i)=>value[i]||''),parts=item.prompt.split(/_{2,}/g);
 function choose(option:string){const next=[...values];next[active]=option;onChange(next);const empty=next.findIndex((v,i)=>!v&&i>active);const first=next.findIndex(v=>!v);setActive(empty>=0?empty:first>=0?first:active);}
 return <div className="inline-blank-answer word-bank-answer"><p className="blank-sentence">{parts.map((part,i)=><React.Fragment key={i}>{part}{i<parts.length-1&&<button className="word-bank-gap" aria-label={`Blank ${i+1}: ${values[i]||'empty'}`} aria-pressed={active===i} disabled={disabled} data-state={disabled?(values[i]===item.blanks[i]?'correct':'wrong'):active===i?'active':'idle'} onClick={()=>setActive(i)}>{values[i]||<span>{i+1}</span>}</button>}</React.Fragment>)}</p><p className="split-answer-help">Tap a gap, then choose an option. You can change any answer before checking.</p><div className="word-bank-options" role="group" aria-label="Word bank">{item.options.map(option=><button key={option} aria-label={`Option ${option}`} disabled={disabled} onClick={()=>choose(option)}>{option}</button>)}</div>{!disabled&&<div className="word-bank-tools"><span role="status">{values.filter(Boolean).length} of {values.length} gaps filled</span><button disabled={!values[active]} onClick={()=>{const next=[...values];next[active]='';onChange(next);}}>Clear selected gap</button></div>}{!disabled&&<Button className="split-submit" disabled={values.some(x=>!x)} onClick={()=>onGrade(values)}>Check answers</Button>}</div>;
}
