import {validateSetups,setupKey} from './quiz-setups.js';
export const normalize=s=>String(s).normalize('NFKC').toLocaleLowerCase().trim().replace(/[^\p{L}\p{N}]/gu,'');
export function distance(a,b){let row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let next=[i];for(let j=1;j<=b.length;j++)next[j]=Math.min(next[j-1]+1,row[j]+1,row[j-1]+(a[i-1]===b[j-1]?0:1));row=next;}return row[b.length];}
export function textGrade(item,value){const actual=normalize(value),answers=[item.answer,...(item.acceptedAnswers||[]),...(item.alt?[item.alt]:[])].map(normalize);if(actual&&answers.includes(actual))return 'correct';if(item.fuzzy!==false&&actual&&answers.some(a=>a.length>=5&&actual.length>=5&&distance(actual,a)<=1&&!/\d/.test(a+actual)))return 'typo';return 'wrong';}
export function scheduled(item,correct,now=new Date()){const interval=correct?Math.min(365,Math.max(1,Math.round((item.interval||0)*2.2))):0;const next=new Date(now);next.setDate(next.getDate()+interval);return {...item,interval,due:next.toISOString().slice(0,10),lastReviewed:now.toISOString(),attempts:(item.attempts||0)+1,lapses:(item.lapses||0)+(correct?0:1)};}
export function weakIds(reports){const stats=new Map();for(const r of reports)for(const q of r.questions||[]){const s=stats.get(q.knowledge_id)||{total:0,wrong:0};s.total++;s.wrong+=!q.correct?1:0;stats.set(q.knowledge_id,s);}return new Set([...stats].filter(([,s])=>s.wrong&&s.wrong/s.total>=.3).map(([id])=>id));}
export function filterQuiz(bank,reports,controls,date=new Date().toISOString().slice(0,10)){const weak=weakIds(reports);const mistakes=new Set(reports.flatMap(r=>(r.questions||[]).filter(q=>!q.correct).map(q=>q.knowledge_id)));let q=bank.filter(x=>(!controls.subject||x.subject===controls.subject)&&(!controls.topic||x.topic===controls.topic)&&(!controls.types.length||controls.types.includes(x.type||'short_answer'))&&(controls.focus==='all'||(controls.focus==='weak'?weak:mistakes).has(x.id))&&(controls.mode==='all'||!x.due||x.due<=date));if(controls.mode==='daily')q.sort((a,b)=>(a.due||'').localeCompare(b.due||''));if(controls.shuffle){q=[...q];for(let i=q.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[q[i],q[j]]=[q[j],q[i]];}}return q.slice(0,controls.count||q.length);}
export function duplicateIds(bank){const groups=new Map();for(const x of bank){const key=normalize(x.prompt)+'|'+normalize(x.answer)+'|'+(x.type||'short_answer');groups.set(key,[...(groups.get(key)||[]),x.id]);}return new Set([...groups.values()].filter(a=>a.length>1).flat());}
export function analytics(reports){const rows=reports.flatMap(r=>r.questions||[]),groups={subject:Object.create(null),topic:Object.create(null),type:Object.create(null)};for(const q of rows)for(const key of Object.keys(groups)){const name=q[key]||'General',s=groups[key][name]||{total:0,correct:0,seconds:0};s.total++;s.correct+=q.correct?1:0;s.seconds+=Number(q.response_time_seconds)||0;groups[key][name]=s;}const mistakes=Object.create(null);for(const q of rows.filter(q=>!q.correct))mistakes[q.knowledge_id]={prompt:q.prompt,count:(mistakes[q.knowledge_id]?.count||0)+1};return {groups,mistakes:Object.values(mistakes).sort((a,b)=>b.count-a.count),trend:[...reports].reverse().slice(-12),total:rows.length};}
export function validateBackup(data,validate){if(data?.app!=='RecallFlow'||data.version!==1||!Array.isArray(data.questions)||!Array.isArray(data.reports)||!Array.isArray(data.streakDays)||!Number.isInteger(data.quizCount)||data.quizCount<0)throw new Error('Choose a complete RecallFlow version 1 backup.');const ids=new Set();const questions=data.questions.map(q=>{if(typeof q.id!=='string'||!q.id||ids.has(q.id))throw new Error('Question IDs must be unique.');ids.add(q.id);return validate(q);});if(data.reports.some(r=>typeof r.id!=='string'||!Array.isArray(r.questions)||!Number.isFinite(r.accuracy)||r.questions.some(q=>typeof q.correct!=='boolean'||typeof q.prompt!=='string')))throw new Error('Invalid report data.');if(data.streakDays.some(d=>typeof d!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(d)))throw new Error('Invalid streak dates.');const p=data.preferences;if(!p||!['light','dark'].includes(p.theme)||!['af_heart','af_bella','am_michael','am_fenrir','bf_emma'].includes(p.voice)||![.8,.9,1,1.1,1.2].includes(p.speed)||!p.quiz||!Number.isInteger(p.quiz.count)||p.quiz.count<0||p.quiz.count>1000||typeof p.quiz.shuffle!=='boolean')throw new Error('Invalid settings.');if(p.quizSetups!==undefined)validateSetups(p.quizSetups);return {...data,questions};}
export function restoreBackup(data){const entries={recallflow_bank_v2:data.questions,recallflow_reports:data.reports,recallflow_streak_days:data.streakDays};const values=Object.fromEntries(Object.entries(entries).map(([k,v])=>[k,JSON.stringify(v)]));Object.assign(values,{recallflow_quiz_count:String(data.quizCount),recallflow_theme:data.preferences.theme,recallflow_kokoro_voice:data.preferences.voice,recallflow_kokoro_speed:String(data.preferences.speed),recallflow_quiz_preferences_v1:JSON.stringify(data.preferences.quiz)});values[setupKey]=JSON.stringify(data.preferences.quizSetups||[]);const old=Object.fromEntries(Object.keys(values).map(k=>[k,localStorage.getItem(k)]));try{for(const [k,v] of Object.entries(values))localStorage.setItem(k,v);}catch(e){for(const [k,v] of Object.entries(old)){if(v===null)localStorage.removeItem(k);else localStorage.setItem(k,v);}throw e;}}

