import {textGrade} from './learning-core.js';
export const questionTypes=[['short_answer','Type answer'],['fill_blank','Fill in the blank'],['single_choice','Multiple choice'],['flashcard','Flashcard'],['true_false','True / False'],['multi_select','Multi-select'],['numeric','Numeric answer'],['matching','Matching'],['ordering','Ordering / sequence'],['cloze','Multi-blank / cloze'],['fill_blank_options','Fill blanks with options']];
export function typeLabel(type){return questionTypes.find(([id])=>id===type)?.[1]||'Type answer';}
export function numericValue(text){const value=String(text).trim();if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(value))return null;const number=Number(value);return Number.isFinite(number)?number:null;}
export function validateQuestion(input){const type=input.type||'short_answer';if(!questionTypes.some(([id])=>id===type))throw new Error('Choose a supported question type.');if(typeof input.prompt!=='string'||!input.prompt.trim())throw new Error('Add a question first.');let answer=String(input.answer??'').trim(),options,correctAnswers,numericTolerance;
if(['single_choice','multi_select'].includes(type)){if(!Array.isArray(input.options)||input.options.length<2||input.options.some(o=>typeof o!=='string'||!o.trim()))throw new Error('Add at least two non-empty choices.');options=input.options.map(o=>o.trim());if(new Set(options).size!==options.length)throw new Error('Each choice must be different.');if(type==='multi_select'){if(!Array.isArray(input.correctAnswers)||!input.correctAnswers.length||input.correctAnswers.some(a=>typeof a!=='string'||!a.trim()))throw new Error('Add the correct choices, one per line.');correctAnswers=input.correctAnswers.map(a=>a.trim());if(new Set(correctAnswers).size!==correctAnswers.length||correctAnswers.some(a=>!options.includes(a)))throw new Error('Every correct answer must match a different choice.');answer=correctAnswers.join('; ');}else if(!options.includes(answer))throw new Error('The correct answer must match one of the choices.');}
if(type==='true_false'){if(!/^(true|false)$/i.test(answer))throw new Error('Choose True or False as the answer.');answer=answer.toLowerCase()==='true'?'True':'False';}
if(type==='numeric'){if(numericValue(answer)===null)throw new Error('Use a finite number for the correct answer.');numericTolerance=numericValue(input.numericTolerance??0);if(numericTolerance===null||numericTolerance<0)throw new Error('Numeric tolerance must be zero or a positive number.');}
if(type==='matching'){if(!Array.isArray(input.pairs)||input.pairs.length<2||input.pairs.some(p=>typeof p.left!=='string'||typeof p.right!=='string'||!p.left.trim()||!p.right.trim())||new Set(input.pairs.map(p=>p.left)).size!==input.pairs.length||new Set(input.pairs.map(p=>p.right)).size!==input.pairs.length)throw new Error('Add at least two unique matching pairs.');answer=input.pairs.map(p=>p.left+' → '+p.right).join('; ');}
if(type==='ordering'){if(!Array.isArray(input.sequence)||input.sequence.length<2||input.sequence.some(x=>typeof x!=='string'||!x.trim())||new Set(input.sequence).size!==input.sequence.length)throw new Error('Add at least two different sequence steps.');answer=input.sequence.join(' → ');}
if(['cloze','fill_blank_options'].includes(type)){if(!Array.isArray(input.blanks)||!input.blanks.length||input.blanks.some(x=>typeof x!=='string'||!x.trim())||(input.prompt.match(/_{2,}/g)||[]).length!==input.blanks.length)throw new Error('Use one ___ marker for each blank answer.');answer=input.blanks.join('; ');}
if(type==='fill_blank_options'){if(!Array.isArray(input.options)||input.options.length<2||input.options.some(x=>typeof x!=='string'||!x.trim()))throw new Error('Add at least two word-bank options.');options=input.options.map(x=>x.trim());if(new Set(options).size!==options.length||input.blanks.some(x=>!options.includes(x)))throw new Error('Use unique options and include every blank answer in the word bank.');}
const imageSafe=x=>typeof x==='string'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(x)&&x.length<2800000;
if(input.image&&!imageSafe(input.image))throw new Error('Use a local PNG, JPEG or WebP image under 2 MB.');if(input.optionImages&&(typeof input.optionImages!=='object'||Object.values(input.optionImages).some(x=>!imageSafe(x))))throw new Error('Invalid image choices.');
if(input.acceptedAnswers&&(!Array.isArray(input.acceptedAnswers)||input.acceptedAnswers.some(a=>typeof a!=='string'||!a.trim())))throw new Error('Alternative answers must be non-empty text.');if(input.tags&&(!Array.isArray(input.tags)||input.tags.some(a=>typeof a!=='string')))throw new Error('Tags must be text.');if(!answer)throw new Error('Add a correct answer first.');return {...input,type,prompt:input.prompt.trim(),answer,options,correctAnswers,numericTolerance};}
export function gradeQuestion(item,given){if(item.type==='fill_blank_options')return Array.isArray(given)&&given.length===item.blanks.length&&item.blanks.every((a,i)=>given[i]===a);if(item.type==='matching')return Array.isArray(given)&&given.length===item.pairs.length&&item.pairs.every((p,i)=>given[i]===p.right);if(item.type==='ordering')return Array.isArray(given)&&JSON.stringify(given)===JSON.stringify(item.sequence);if(item.type==='cloze')return Array.isArray(given)&&given.length===item.blanks.length&&item.blanks.every((a,i)=>textGrade({answer:a,fuzzy:item.fuzzy},given[i])!=='wrong');if(item.type==='multi_select'){const expected=new Set(item.correctAnswers||[]),actual=new Set(Array.isArray(given)?given:[]);return expected.size>0&&expected.size===actual.size&&[...expected].every(value=>actual.has(value));}if(item.type==='numeric'){const value=numericValue(given),expected=numericValue(item.answer),tolerance=Number(item.numericTolerance||0);return value!==null&&expected!==null&&Number.isFinite(tolerance)&&tolerance>=0&&Math.abs(value-expected)<=tolerance+Number.EPSILON*Math.max(1,Math.abs(value),Math.abs(expected))*4;}if(['single_choice','true_false'].includes(item.type))return String(given).trim()===item.answer;return textGrade(item,given)!=='wrong';}
export function missedItems(attempts,bank){const ids=new Set(attempts.filter(attempt=>!attempt.correct).map(attempt=>attempt.knowledge_id));return bank.filter(item=>ids.has(item.id));}
